### ISSUE TITLE
/weapons-wiki failed at requesting data

### ISSUE THREAD

**Issue by ghost** [Snekw/Wf#8]
![image](https://user-images.githubusercontent.com/87491799/162971516-3d58960e-da7a-4430-9dd0-e11952539edd.png)

**Comment by Snekw** [comment]
Fixed in 7d0fe66c0009ac6723c9cbb3115b2448081e4b3d

Note that the returned data has changed structure. The change on wiki side that broke the API changed the data structure a lot.
